### ISSUE TITLE
Artus Outputs

### ISSUE THREAD

**Issue by rfriese** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#18]
Hi all,

again I got a problem with the links in ArtusOutputs. When submitting jobs with crab I got an infinite loop. This is another problem additionaly to the one when compiling the KITHiggs repo for the first time.

https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/tree/master/data/ArtusOutputs

As it's not really used anyway atm ( last link is still from 2015) I'd suggest to delete all the symlinks. I'd suggest to replace this with entries in the README file pointing to outputs of full analysis runs. What do you think?

Cheers,
Raphael

**Comment by fcolombo** [comment]
I'm fine with it, if the problems are more than the advantages.
The idea behind the symlinks was to give every user the possibility to retrieve immediately the latest Artus outputs, for example for doing a quick plot without having to re-run the analysis.
I don't know if this is still needed: I have more the impression that we all tend to run our (sometimes different) analyses on our own, which by the way is perfectly fine since in this way we all have a working knowledge of how this is done. A path in the README file will work just as fine.
Of course we need to keep the README up to date, but this is would be true also for the symlinks (and is not done so regularly at the moment :-) )

**Comment by thomas-mueller** [comment]
Hi Raphael,

Firstly, when you think about deleting the symlinks there, you should 
also remove/uncomment their creation in the python wrapper.

I find the symlinks quite useful when one has to share outputs with 
somebody else, but I also know, that I was not really used. I also tried 
to design the wrapper such that it creates the outputs always in the 
same path, such that you can easily find and use the outputs of 
colleagues. But also this mechanism is not well accepted and people 
prefer to have custom directory structures. So I do not know how to 
improve things. Maybe we just do not want to share outputs so much and 
in the rare case we want it, we can ask for a path? (What about busy 
times, where it takes to long to ask, like late evenings/weekends?)

I think, that the only problem are the GC outputs. Maybe we can just 
delete them in case all jobs succeeded?

Cheers,
Thomas


Am 04.04.2016 um 11:11 schrieb Raphael Friese:

**Comment by thomas-mueller** [comment]
Paths in READMEs are as bad as the links to the latest sync files/limit inputs in the CERN group. You always have to find another file first, open it and copy it before you can access the actual file you are looking for. Additionally, they will be outdated even more quickly than real symlinks (comparable to twiki documentations).

**Comment by rfriese** [comment]
Since one basically always has to ask if the links are up-to-date I think there's always the need for communication. The README file solution has the advantage that one can document better what is in there.

But atm I think no one really uses this symlinks and therefore I can remove them and comment out the feature to create them in the wrapper.
