### ISSUE TITLE
Bug related to static methods in samples_run2_201X.py?

### ISSUE THREAD

**Issue by anehrkor** [cms-analysis/HiggsAnalysis-KITHiggsToTauTau#36]
Hi,

since I just found a bug in [code that I wrote](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/commit/2f04dfc4f29fbf78e8dd37f1dd9e8fc010abef33) related to static methods, I noticed these two static methods:
- [method 1](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/b746303f3c23409174517968069da74c3e08fb66/python/plotting/configs/samples_run2_2016.py#L33-L39)
- [method 2](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/blob/074c819f694495d22882eb331f5b872faae1a5b9/python/plotting/configs/samples_run2_2015.py#L43-L52)

To my (limited) understanding, the second method will not override the first one since the first one is declared static. Is there any need for either of these methods being static? Or can this be removed to actually override the method?

Cheers,
Alex

**Comment by rfriese** [comment]
Hi, a comment on the "staticmethod" thing that has somehow become standard. Many of these functions are basically not member functions of a class in a way that they act on internal states, but the classes' sole purpose is to show that the functions somehow belong together.

In that way, it's a lot more convenient to be able to call these helper functions externally without creating an instance of the class. This also makes the code a lot more readable and the user can be safe that there's no interference of any internal state of the class.

I think it would be a good idea to use an improved data structure for the 2017 config.

I suggest to close the issue since there hasn't been any action on it for nearly a year.

**Comment by anehrkor** [comment]
I wanted to bring this to the attention of people using samples_run2_2015.py. I do not have the time to investigate this.

If this isn't an issue, we can close it. But so far nobody has confirmed that it in fact isn't. So I would prefer the issue stay open until someone who uses the potentially problematic file has testet it and says otherwise.
